### ISSUE TITLE
naive-ui nuxt conflict with tailwindcss

### ISSUE THREAD

**Issue by tiagomatosweb** [huntersofbook/naive-ui-nuxt#1]
I've installed the @huntersofbook/naive-ui-nuxt package but I'm still facing conflict issue with tailwindcss. 

Seems like some component from naive-ui are being loaded before tailwindcss as shown in this image
https://www.awesomescreenshot.com/image/39982521?key=6506068fe01b3700daa5cd4fd4c47f89

And because of this, my buttons have transparent background which breaks the layout.

Any idea?

**Comment by productdevbook** [comment]
https://github.com/huntersofbook/naive-ui-nuxt/issues/4#issuecomment-1560956255
